/**
     *Formulario grafico para mostrar la pantalla que permita registrar los campos (Caso de Uso)
     *"Diseñar la interfaz gráfica, utilizando la vista de diseño que brinda NetBeans. Para ayuda sobre esto, está
disponible el “Instructivo de Diseño de Interfaces Visuales con Java Swing en NetBeans IDE.”
     */
package gui;


import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import modelo_clases.EmpresaAdministradora;
import modelo_clases.Establecimiento;
import modelo_clases.Lote;
import modelo_clases.Suelo;


/**
 * @author Ibarra Gustavo | ibarrags@gmail.com 
 */
public class PantallaRegistrarCampos extends javax.swing.JFrame {
  
    private final TablaLoteModel tablaLotesModel;
    
    private List<Suelo> suelos;
    private EmpresaAdministradora empresaAdministradora;
    private Establecimiento establecimiento;
    private Lote lote;
    
    int superficieEstablecimiento;
    int superficieLote;
    
    public PantallaRegistrarCampos(List<Suelo> tiposDeSuelos, EmpresaAdministradora unaEmpresa, Establecimiento unEstablecimiento,Lote unLote) {
        
        this.empresaAdministradora = unaEmpresa;
        this.suelos = tiposDeSuelos;
        this.establecimiento= unEstablecimiento;
        this.lote= unLote;
        
        this.tablaLotesModel = new TablaLoteModel(this.establecimiento.lotes());
        
        initComponents();
        Suelo unSueloSeleccionado= (Suelo) ComboBoxTipoSuelo.getSelectedItem();
        this.lote.suelo(unSueloSeleccionado);        
        
        txtSuperficie.setEditable(false);
        txtNumeroLote.setEditable(false);
        txtSuperficieLote.setEditable(false);
        ComboBoxTipoSuelo.setEditable(false);
        LabelErrorNombre.setVisible(false);   
        LabelErrorNroLote.setVisible(false);  
        LabelErrorSuperficie.setVisible(false);       
        jButtonAgregrLote.setEnabled(false);
        LabelErrorSuperficieLote.setVisible(false);   
        ButtonQuitar.setEnabled(false);
        ButtonEditar.setEnabled(false);
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtSuperficie = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombreEstablecimiento = new javax.swing.JTextField();
        LabelErrorNombre = new javax.swing.JLabel();
        LabelErrorSuperficie = new javax.swing.JLabel();
        panelLotesIngresados = new javax.swing.JPanel();
        JScrollLotes = new javax.swing.JScrollPane();
        tablaLotes = new javax.swing.JTable();
        ButtonQuitar = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtNumeroLote = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSuperficieLote = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LabelErrorNroLote = new javax.swing.JLabel();
        ComboBoxTipoSuelo = new javax.swing.JComboBox<>();
        jButtonAgregrLote = new javax.swing.JButton();
        LabelErrorSuperficieLote = new javax.swing.JLabel();
        ButtonCancelar = new javax.swing.JButton();
        ButtonRegistrarEstablecimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Establecimiento");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Establecimiento", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setToolTipText("Datos Establecimiento");

        jLabel8.setText("Nombre");

        txtSuperficie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSuperficieFocusLost(evt);
            }
        });

        jLabel9.setText("Superficie");

        txtNombreEstablecimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreEstablecimientoFocusLost(evt);
            }
        });

        LabelErrorNombre.setText("Nombre en uso. Ingrese otro nombre");

        LabelErrorSuperficie.setText("Ingrese un valor mayor a cero");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelErrorSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombreEstablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(LabelErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEstablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(LabelErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelErrorSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(50, 50, 50))
        );

        panelLotesIngresados.setBorder(javax.swing.BorderFactory.createTitledBorder("Lotes Ingresados. Marcar un lote"));

        tablaLotes.setModel(tablaLotesModel);
        tablaLotes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaLotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLotesMouseClicked(evt);
            }
        });
        JScrollLotes.setViewportView(tablaLotes);

        ButtonQuitar.setText("Quitar");
        ButtonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonQuitarActionPerformed(evt);
            }
        });

        ButtonEditar.setText("Editar");
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLotesIngresadosLayout = new javax.swing.GroupLayout(panelLotesIngresados);
        panelLotesIngresados.setLayout(panelLotesIngresadosLayout);
        panelLotesIngresadosLayout.setHorizontalGroup(
            panelLotesIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLotesIngresadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLotesIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JScrollLotes, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLotesIngresadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonEditar)
                        .addGap(31, 31, 31)
                        .addComponent(ButtonQuitar)))
                .addContainerGap())
        );
        panelLotesIngresadosLayout.setVerticalGroup(
            panelLotesIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLotesIngresadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JScrollLotes, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(panelLotesIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonEditar)
                    .addComponent(ButtonQuitar)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Lotes"));

        jLabel11.setText("Numero");

        txtNumeroLote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroLoteFocusLost(evt);
            }
        });

        jLabel12.setText("Superficie");

        txtSuperficieLote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSuperficieLoteFocusLost(evt);
            }
        });

        jLabel2.setText("Tipo Suelo");

        LabelErrorNroLote.setText("Error con nro lote ingresado");

        ComboBoxTipoSuelo.setModel(new javax.swing.DefaultComboBoxModel(suelos.toArray()));
        ComboBoxTipoSuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoSueloActionPerformed(evt);
            }
        });

        jButtonAgregrLote.setText("Agregar");
        jButtonAgregrLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregrLoteActionPerformed(evt);
            }
        });

        LabelErrorSuperficieLote.setText("Error con nro superficie ingresado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButtonAgregrLote))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabelErrorNroLote, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumeroLote)
                                    .addComponent(txtSuperficieLote)
                                    .addComponent(ComboBoxTipoSuelo, 0, 200, Short.MAX_VALUE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelErrorSuperficieLote, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSuperficieLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxTipoSuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelErrorNroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelErrorSuperficieLote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAgregrLote))
        );

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        ButtonRegistrarEstablecimiento.setText("Registrar Establecimiento");
        ButtonRegistrarEstablecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistrarEstablecimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelLotesIngresados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonRegistrarEstablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLotesIngresados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancelar)
                    .addComponent(ButtonRegistrarEstablecimiento))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroLoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroLoteFocusLost
        
        if (  txtNumeroLote.getText().isEmpty() == false)
            txtSuperficieLote.setEditable(true);            
        else        
            LabelErrorNroLote.setVisible(true); 
        
    }//GEN-LAST:event_txtNumeroLoteFocusLost

    private void txtSuperficieLoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSuperficieLoteFocusLost
        
        jButtonAgregrLote.setEnabled(true);
        ButtonQuitar.setEnabled(true);
        ButtonEditar.setEnabled(true);
                    
    }//GEN-LAST:event_txtSuperficieLoteFocusLost

    private void jButtonAgregrLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregrLoteActionPerformed
        
        
        if (this.establecimiento.agregarLote(this.lote, Integer.parseInt(txtNumeroLote.getText()),Integer.parseInt(txtSuperficieLote.getText()) ) == false) 
        {
            LabelErrorNroLote.setVisible(true);   
            LabelErrorSuperficieLote.setVisible(true);   

        }
        else
        {
            LabelErrorNroLote.setVisible(false); 
            LabelErrorSuperficieLote.setVisible(false);   
            
            Lote ultimoLote =this.establecimiento.lotes().get(establecimiento.lotes().size() - 1);           
            ultimoLote.superficie(this.superficieLote);
        
            Suelo unSueloSeleccionado= (Suelo) ComboBoxTipoSuelo.getSelectedItem();
            ultimoLote.suelo(unSueloSeleccionado);
                 
            this.superficieLote = Integer.parseInt(txtSuperficieLote.getText());
            ultimoLote.superficie(this.superficieLote);
         
            tablaLotesModel.setLotes(this.establecimiento.lotes());
            tablaLotesModel.fireTableDataChanged();

        }            
       
    }//GEN-LAST:event_jButtonAgregrLoteActionPerformed

    private void tablaLotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLotesMouseClicked

    }//GEN-LAST:event_tablaLotesMouseClicked

    private void ComboBoxTipoSueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoSueloActionPerformed
        
        
    }//GEN-LAST:event_ComboBoxTipoSueloActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonRegistrarEstablecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistrarEstablecimientoActionPerformed
        
        new PantallConfirmarRegistrarCampos(this.establecimiento).setVisible(true);
    }//GEN-LAST:event_ButtonRegistrarEstablecimientoActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
       JOptionPane.showMessageDialog(null, "Funcionalidad aun no implementado");
    }//GEN-LAST:event_ButtonEditarActionPerformed

    private void ButtonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonQuitarActionPerformed
        JOptionPane.showMessageDialog(null, "Funcionalidad aun no implementado");
    }//GEN-LAST:event_ButtonQuitarActionPerformed

    // controla la existencia de un Establecimiento con el mismo nombre imgresado.
    private void txtNombreEstablecimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreEstablecimientoFocusLost

        if ( ! txtNombreEstablecimiento.getText().isEmpty())
        {

            this.establecimiento.nombre(txtNombreEstablecimiento.getText());

            if ( this.empresaAdministradora.agregarEstablecimiento(establecimiento) == false)
            {
                LabelErrorNombre.setVisible(true);

            }
            else
            {
                txtSuperficie.setEditable(true);
                LabelErrorNombre.setVisible(false);
            }
        } else

        LabelErrorNombre.setVisible(true);

    }//GEN-LAST:event_txtNombreEstablecimientoFocusLost

    private void txtSuperficieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSuperficieFocusLost

        if ( txtSuperficie.getText().isEmpty() == false ){
            this.superficieEstablecimiento = Integer.parseInt(txtSuperficie.getText());
            if ( this.superficieEstablecimiento < 1 )
            LabelErrorSuperficie.setVisible(true);
            else
            {
                this.establecimiento.superficieEstablecimiento(this.superficieEstablecimiento);
                txtNumeroLote.setEditable(true);
                LabelErrorSuperficie.setVisible(false);
                txtSuperficie.setEditable(false);
                txtNombreEstablecimiento.setEditable(false);
            }
        }
        else
        LabelErrorSuperficie.setVisible(true);

    }//GEN-LAST:event_txtSuperficieFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistrarCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PantallaRegistrarCampos().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonQuitar;
    private javax.swing.JButton ButtonRegistrarEstablecimiento;
    private javax.swing.JComboBox<String> ComboBoxTipoSuelo;
    private javax.swing.JScrollPane JScrollLotes;
    private javax.swing.JLabel LabelErrorNombre;
    private javax.swing.JLabel LabelErrorNroLote;
    private javax.swing.JLabel LabelErrorSuperficie;
    private javax.swing.JLabel LabelErrorSuperficieLote;
    private javax.swing.JButton jButtonAgregrLote;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelLotesIngresados;
    private javax.swing.JTable tablaLotes;
    private javax.swing.JTextField txtNombreEstablecimiento;
    private javax.swing.JTextField txtNumeroLote;
    private javax.swing.JTextField txtSuperficie;
    private javax.swing.JTextField txtSuperficieLote;
    // End of variables declaration//GEN-END:variables
}
